workflows:
  android-build:
    name: Android Build Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Pre-build script
        script: |
          #!/bin/sh
          set -e
          echo ">>> Checking for android directory..."
          if [ ! -d "android" ]; then
            echo "android/ klasörü eksik, flutter create . ile oluşturuluyor..."
            flutter create .
          fi
          flutter pub get

      - name: Build Android APK
        script: |
          flutter build apk --debug
