workflows:
  android-workflow:
    name: Android Build Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      flutter_version: 3.22.0
      vars:
        GRADLE_OPTS: "-Xmx4096m -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs='-Xmx4096m'"
    scripts:
      - name: Ensure Android directory exists
        script: |
          if [ ! -d "android" ]; then
            echo "Creating missing Android directory..."
            flutter create .
          fi

      - name: Clean and get dependencies
        script: |
          flutter clean
          flutter pub get

      - name: Build Android APK (debug)
        script: |
          flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk

    cache:
      cache_paths:
        - ~/.pub-cache
        - android/.gradle
