workflows:
  android-workflow:
    name: Android Build Workflow
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Prepare Android directory if missing
        script: |
          if [ ! -d "android" ]; then
            flutter create .
          fi
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
